// Code generated by "stringer -type=Type"; DO NOT EDIT

package lex

import "fmt"

const _Type_name = "UnknownTermIntegerStringAtomTrueFalseNilDotWordOpenParenCloseParenCommaEqualIntoOpenBraceCloseBraceSemiNewlineImportDefClassCommentIVarHasIsIfIncDecWhileUpDot"

var _Type_index = [...]uint8{0, 7, 11, 18, 24, 28, 32, 37, 40, 43, 47, 56, 66, 71, 76, 80, 89, 99, 103, 110, 116, 119, 124, 131, 135, 138, 140, 142, 145, 148, 153, 158}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
